// Generates src/icons/icons.ts from Tabler Icons (MIT, https://tabler.io/icons).
//
// Components ship with this curated set so they work with no setup. Apps can add
// any other Tabler icon with registerIcons(). A full, tree-shakable icon package
// (@eduportdesign/icons) is planned.
//
// Usage: pnpm icons   (edit ICONS below, then re-run)
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ICONS = [
  // Used inside components
  'check', 'minus', 'x', 'chevron-down', 'chevron-up', 'chevron-left', 'chevron-right', 'selector',
  'info-circle', 'circle-check', 'alert-triangle', 'alert-circle', 'user',
  // General purpose
  'plus', 'search', 'filter', 'adjustments-horizontal', 'settings', 'dots', 'dots-vertical', 'menu-2',
  'home', 'layout-dashboard', 'school', 'book', 'books', 'notebook', 'certificate', 'clipboard-list',
  'calendar', 'calendar-event', 'clock', 'bell', 'mail', 'message-circle', 'send', 'phone',
  'users', 'user-plus', 'user-circle', 'id-badge-2', 'lock', 'lock-open', 'key', 'shield-check', 'logout', 'login',
  'edit', 'pencil', 'trash', 'copy', 'download', 'upload', 'share', 'link', 'external-link', 'paperclip',
  'file', 'file-text', 'folder', 'photo', 'video', 'microphone', 'player-play', 'player-pause',
  'star', 'heart', 'bookmark', 'flag', 'tag', 'eye', 'eye-off', 'refresh', 'arrow-left', 'arrow-right',
  'arrow-up', 'arrow-down', 'sun', 'moon', 'world', 'map-pin', 'chart-bar', 'chart-pie', 'trophy',
  'help-circle', 'question-mark', 'bulb', 'sparkles', 'cloud-upload', 'printer', 'credit-card', 'wallet',
];

// The package's exports map hides package.json, so read it from node_modules directly.
const root = new URL('../node_modules/@tabler/icons/', import.meta.url).pathname;
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));

const entries = ICONS.map((name) => {
  const svg = readFileSync(join(root, 'icons/outline', `${name}.svg`), 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/<path stroke="none" d="M0 0h24v24H0z" fill="none"\s*\/>/, '')
    .replace(/\s*\n\s*/g, '')
    .replace(/\s+\/>/g, '/>')
    .trim();
  return `  '${name}': '${inner}',`;
});

writeFileSync(
  new URL('../src/icons/icons.ts', import.meta.url),
  `// Generated by scripts/generate-icons.mjs from @tabler/icons ${version} (MIT). Do not edit.\n` +
    `export const icons: Record<string, string> = {\n${entries.join('\n')}\n};\n`,
);
console.log(`Wrote ${ICONS.length} icons.`);
